### PR TITLE
Add normal and reverse ordering by SKU

### PR DESCRIPTION
**Pull request by freeaanzee**
I needed this for my own project but it would be handy if it were to be included in the main plugin :). Translations should be added to the PO-file of course, now I just entered the Dutch descriptions.

### CODE REVIEW

**Comment by bekarice** [comment]
Hey @freeaanzee so sorry I missed this one! Didn't see an alert come in for this PR, and I typically only check this repo around doing compatibility updates.

I'm afraid SKU sorting is something we've consciously omitted from the plugin, so I'm going to close this PR. I really appreciate you taking the time to contribute it, so thank you!
 
As many merchants use alphanumeric SKUs, they expect sorting by SKU use a natural sort, which isn't possible by default with WP Query. While it would work for some stores, since we can't do a natural (alphanumeric) sort, (ie `ABC32` would be sorted after `ABC3` and before `ABC4`), this will likely cause as many questions as it solves in the support forum (alas, using leading zeros isn't as popular as we'd hope!). We've opted to share a snippet for SKU sorting where relevant instead.

Thanks again!

**Comment by freeaanzee** [comment]
Haha,

No problem! And I totally get that this unexpected behaviour can raise a lot of support questions. We have strictly numerical SKU’s (and just one leftover product with a nice leading zero) so I didn’t think about that.

I was new to GitHub, so maybe I was a bit too eager to contribute :). Where do I find the SKU sorting snippet you mention? Since my quick fix isn't safe for upgrades ...

Frederik

**Comment by bekarice** [comment]
@freeaanzee sure thing, here's the snippet I've used: https://gist.github.com/bekarice/1883b7e678ec89cc8f4d

Since your SKUs are only numerical, I'd change `$args['orderby'] = 'meta_value';` to `$args['orderby'] = 'meta_value_num';` instead so the numbers sort properly.

**Comment by freeaanzee** [comment]
Thx!

**Pull request closed without merging**
